### ISSUE TITLE
Complete project.

### ISSUE THREAD

**Issue by Ryano2022** [Ryano2022/ATU-Year-4-Emerging-Technologies#5]
- [x] Create Eliza chat bot.

**Comment by Revan190** [comment]
Hello, can i get this issue for work?

**Comment by Ryano2022** [comment]
> Hello, can i get this issue for work?

sorry, who are you? what do you mean for work?

**Comment by Revan190** [comment]
> > Hello, can i get this issue for work?
> 
> sorry, who are you? what do you mean for work?

Oh, sorry, where is my manners.
I`m Revan190, beginner developer in Python, java, SQL and etc. I just looking for issues and make free work like internship.
And "for work" means, that i give this issue and work with this problem/project.

**Comment by Ryano2022** [comment]
> > > Hello, can i get this issue for work?
> > 
> > 
> > sorry, who are you? what do you mean for work?
> 
> Oh, sorry, where is my manners. I`m Revan190, beginner developer in Python, java, SQL and etc. I just looking for issues and make free work like internship. And "for work" means, that i give this issue and work with this problem/project.

I see, but I can't exactly give you these issues as it is a college project that I myself have to do for my grade. How did you even come across this issue?

**Comment by Revan190** [comment]
> > > > Hello, can i get this issue for work?
> > > 
> > > 
> > > sorry, who are you? what do you mean for work?
> > 
> > 
> > Oh, sorry, where is my manners. I`m Revan190, beginner developer in Python, java, SQL and etc. I just looking for issues and make free work like internship. And "for work" means, that i give this issue and work with this problem/project.
> 
> I see, but I can't exactly give you these issues as it is a college project that I myself have to do for my grade. How did you even come across this issue?

Oh, i understand now...
How did i become? Just looking in GitHub search engine with request "Make Chat Bot".
I am sorry for this misunderstood.
